version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: footprints
    environment:
      DATABASE_URL: mysql2://root:password@mysql/footprints
      MYSQL_HOST: mysql # Sets default host for mysql-client CLI
      MYSQL_PWD: password # Sets default password for mysql-client CLI
      RAILS_ENV: development
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    # Allow support for irb, pry, etc
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
